services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/stella_lite?sslmode=disable"
      BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
      BETTER_AUTH_URL: "${BASE_URL}"
      NEXT_PUBLIC_APP_URL: "${BASE_URL}"
      LINE_CLIENT_ID: "${LINE_CLIENT_ID}"
      LINE_CLIENT_SECRET: "${LINE_CLIENT_SECRET}"
      ADMIN_LINE_ID: "${ADMIN_LINE_ID}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stella_lite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
